"""Persistence boundary for owner-scoped lifecycle enforcement."""

from __future__ import annotations

from collections.abc import Callable
from typing import Protocol, Self

from yuno.modules.data_lifecycle.domain import CleanupIntent


class DataLifecycleRepository(Protocol):
    def expire_diagnostics(
        self, owner_id: str, cutoff: str, expired_at: str
    ) -> int: ...
    def expire_interviews(self, owner_id: str, cutoff: str) -> int: ...
    def purge_job_exhaust(self, owner_id: str, cutoff: str) -> int: ...
    def expire_job_events(
        self, owner_id: str, cutoff: str, keep_newest: int
    ) -> int: ...
    def expire_runner_outputs(self, owner_id: str, cutoff: str) -> int: ...
    def expire_export_packages(self, owner_id: str, cutoff: str) -> int: ...
    def expire_export_operations(self, owner_id: str, cutoff: str) -> int: ...
    def purge_goal_bodies(self, owner_id: str, goal_id: str, now: str) -> int: ...
    def purge_import_bodies(self, owner_id: str, import_id: str) -> int: ...
    def purge_interview_bodies(self, owner_id: str, run_id: str) -> int: ...
    def add_cleanup_intent(self, intent: CleanupIntent) -> None: ...
    def list_pending_cleanup_intents(
        self, owner_id: str
    ) -> tuple[CleanupIntent, ...]: ...
    def finish_cleanup_intent(
        self, owner_id: str, intent_id: str, completed_at: str
    ) -> bool: ...
    def fail_cleanup_intent(
        self, owner_id: str, intent_id: str, classification: str, updated_at: str
    ) -> bool: ...


class DataLifecycleUnitOfWork(Protocol):
    data_lifecycle: DataLifecycleRepository

    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...
    def commit(self) -> None: ...


DataLifecycleUnitOfWorkFactory = Callable[[], DataLifecycleUnitOfWork]
