from __future__ import annotations

from typing import Protocol

from yuno.modules.search.domain import SearchIndexState, SearchResult


class SearchRepositoryPort(Protocol):
    def state(self, owner_id: str) -> SearchIndexState: ...
    def search(
        self, owner_id: str, goal_id: str, query: str, types: tuple[str, ...]
    ) -> tuple[SearchResult, ...]: ...
    def mark_rebuilding(self, owner_id: str, job_id: str) -> None: ...
    def mark_failed(self, owner_id: str, job_id: str, diagnostic: str) -> None: ...
    def rebuild(self, owner_id: str, job_id: str) -> str: ...
    def source_watermark(self, owner_id: str) -> str: ...


class SearchUnitOfWork(Protocol):
    search: SearchRepositoryPort

    def commit(self) -> None: ...
