"""initial identity and audit

Revision ID: 442e2f56adb9
Revises: 
Create Date: 2026-08-11 17:01:37.131299

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '442e2f56adb9'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_AUDIT_EVENTS_NO_UPDATE_TRIGGER = "trg_audit_events_no_update"
_AUDIT_EVENTS_NO_DELETE_TRIGGER = "trg_audit_events_no_delete"
_AUDIT_EVENTS_NO_INSERT_REPLACE_TRIGGER = "trg_audit_events_no_insert_replace"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.CheckConstraint("kind IN ('local_builtin')", name=op.f('ck_owners_kind_valid')),
    sa.CheckConstraint("status IN ('active','tombstoned')", name=op.f('ck_owners_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_owners')),
    sa.UniqueConstraint('kind', name=op.f('uq_owners_kind'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Text(), nullable=False),
    sa.Column('goal_id', sa.Text(), nullable=True),
    sa.Column('actor_role', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('before_hash', sa.Text(), nullable=True),
    sa.Column('after_hash', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_audit_events_owner_id_owners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('id', 'owner_id', name=op.f('uq_audit_events_id'))
    )
    op.create_index(
        'ix_audit_events_owner_occurred', 'audit_events', ['owner_id', 'occurred_at'], unique=False
    )

    # Append-only guard (spec §4.1, §4.7): `audit_events` rejects UPDATE/DELETE
    # at the database layer, not just through repository conventions. SQLite
    # has no native immutable-table option, so a BEFORE trigger that always
    # aborts is the enforcement mechanism.
    #
    # These two triggers alone are not sufficient: SQLite's `INSERT OR
    # REPLACE` (and `INSERT ... ON CONFLICT DO UPDATE` targeting a row that
    # would be inserted, i.e. the insert side of an upsert) resolves a
    # PRIMARY KEY/UNIQUE conflict by deleting the conflicting row internally
    # and then inserting the new values -- using neither the UPDATE nor the
    # DELETE keyword. That internal delete only fires DELETE triggers when
    # `PRAGMA recursive_triggers` is on, which it is not (see
    # `infrastructure/database.py`), so `trg_audit_events_no_delete` never
    # sees it and a single `INSERT OR REPLACE` statement can silently
    # rewrite every column of an existing row. `trg_audit_events_no_insert_replace`
    # below closes that gap with a BEFORE INSERT existence guard, which
    # fires ahead of SQLite's conflict-resolution step regardless of which
    # conflict algorithm the statement requests. It lives in the schema
    # (not a connection-level pragma), so it protects every connection,
    # including a raw `sqlite3` session from an external tool.
    #
    # WARNING: `migrations/env.py` sets `render_as_batch=True`. SQLite batch
    # mode implements `ALTER TABLE` as rename -> recreate -> copy -> drop;
    # these triggers are raw SQL, invisible to SQLAlchemy metadata, so any
    # future `batch_alter_table("audit_events", ...)` migration silently
    # drops all three of them. That migration must explicitly recreate
    # `trg_audit_events_no_update`, `trg_audit_events_no_delete` and
    # `trg_audit_events_no_insert_replace` afterward.
    op.execute(
        f"""
        CREATE TRIGGER {_AUDIT_EVENTS_NO_UPDATE_TRIGGER}
        BEFORE UPDATE ON audit_events
        BEGIN
            SELECT RAISE(ABORT, 'audit_events is append-only: UPDATE is not permitted');
        END;
        """
    )
    op.execute(
        f"""
        CREATE TRIGGER {_AUDIT_EVENTS_NO_DELETE_TRIGGER}
        BEFORE DELETE ON audit_events
        BEGIN
            SELECT RAISE(ABORT, 'audit_events is append-only: DELETE is not permitted');
        END;
        """
    )
    op.execute(
        f"""
        CREATE TRIGGER {_AUDIT_EVENTS_NO_INSERT_REPLACE_TRIGGER}
        BEFORE INSERT ON audit_events
        WHEN EXISTS (SELECT 1 FROM audit_events WHERE id = NEW.id)
        BEGIN
            SELECT RAISE(ABORT, 'audit_events is append-only: INSERT that overwrites an existing id is not permitted');
        END;
        """
    )

    op.create_table('owner_role_grants',
    sa.Column('owner_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('assigned_at', sa.Text(), nullable=False),
    sa.Column('assigned_by_owner_id', sa.Text(), nullable=False),
    sa.CheckConstraint("role IN ('learner','designated_editorial_approver')", name=op.f('ck_owner_role_grants_role_valid')),
    sa.ForeignKeyConstraint(['assigned_by_owner_id'], ['owners.id'], name=op.f('fk_owner_role_grants_assigned_by_owner_id_owners')),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name=op.f('fk_owner_role_grants_owner_id_owners')),
    sa.PrimaryKeyConstraint('owner_id', 'role', name=op.f('pk_owner_role_grants'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owner_role_grants')
    op.execute(f"DROP TRIGGER {_AUDIT_EVENTS_NO_INSERT_REPLACE_TRIGGER}")
    op.execute(f"DROP TRIGGER {_AUDIT_EVENTS_NO_DELETE_TRIGGER}")
    op.execute(f"DROP TRIGGER {_AUDIT_EVENTS_NO_UPDATE_TRIGGER}")
    op.drop_index('ix_audit_events_owner_occurred', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('owners')
    # ### end Alembic commands ###
