"""learner roadmap overlays

Revision ID: 6834679f0af4
Revises: d3f4a1c8e205
Create Date: 2026-08-12 01:46:54.912863

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6834679f0af4"
down_revision: str | Sequence[str] | None = "d3f4a1c8e205"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learner_corrections",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("goal_id", sa.Text(), nullable=False),
        sa.Column("topic_stable_id", sa.Text(), nullable=False),
        sa.Column("correction_type", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("supersedes_correction_id", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "correction_type IN ('correction','confirmation','gap','transfer-confirmation')",
            name=op.f("ck_learner_corrections_correction_type_valid"),
        ),
        sa.CheckConstraint(
            "value IN ('likely-known','partial','unverified','new')",
            name=op.f("ck_learner_corrections_value_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["goal_id", "owner_id"],
            ["goal_workspaces.id", "goal_workspaces.owner_id"],
            name="fk_learner_corrections_goal_owner",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owners.id"],
            name=op.f("fk_learner_corrections_owner_id_owners"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_correction_id"],
            ["learner_corrections.id"],
            name=op.f(
                "fk_learner_corrections_supersedes_correction_id_learner_corrections"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learner_corrections")),
        sa.UniqueConstraint(
            "id", "owner_id", "goal_id", name="uq_learner_corrections_id_owner_goal"
        ),
    )
    with op.batch_alter_table("learner_corrections", schema=None) as batch_op:
        batch_op.create_index(
            "ix_learner_corrections_owner_goal_topic",
            ["owner_id", "goal_id", "topic_stable_id", "created_at"],
            unique=False,
        )

    op.create_table(
        "roadmap_idempotency",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("goal_id", sa.Text(), nullable=False),
        sa.Column("operation", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("request_hash", sa.Text(), nullable=False),
        sa.Column("response_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "length(trim(operation)) > 0",
            name=op.f("ck_roadmap_idempotency_operation_non_blank"),
        ),
        sa.CheckConstraint(
            "length(trim(idempotency_key)) > 0",
            name=op.f("ck_roadmap_idempotency_idempotency_key_non_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["goal_id", "owner_id"],
            ["goal_workspaces.id", "goal_workspaces.owner_id"],
            name="fk_roadmap_idempotency_goal_owner",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owners.id"],
            name=op.f("fk_roadmap_idempotency_owner_id_owners"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roadmap_idempotency")),
        sa.UniqueConstraint(
            "id", "owner_id", "goal_id", name="uq_roadmap_idempotency_id_owner_goal"
        ),
        sa.UniqueConstraint(
            "owner_id",
            "operation",
            "idempotency_key",
            name="uq_roadmap_idempotency_command",
        ),
    )

    op.create_table(
        "learning_states",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("goal_id", sa.Text(), nullable=False),
        sa.Column("topic_stable_id", sa.Text(), nullable=False),
        sa.Column("graph_version_id", sa.Text(), nullable=False),
        sa.Column("classification", sa.Text(), nullable=False),
        sa.Column("origin", sa.Text(), nullable=False),
        sa.Column("recommended_depth", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("derivation_version", sa.Text(), nullable=False),
        sa.Column("input_hash", sa.Text(), nullable=False),
        sa.Column("derived_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "classification IN ('likely-known','partial','unverified','new')",
            name=op.f("ck_learning_states_classification_valid"),
        ),
        sa.CheckConstraint(
            "length(trim(origin)) > 0", name=op.f("ck_learning_states_origin_non_blank")
        ),
        sa.ForeignKeyConstraint(
            ["goal_id", "owner_id"],
            ["goal_workspaces.id", "goal_workspaces.owner_id"],
            name="fk_learning_states_goal_owner",
        ),
        sa.ForeignKeyConstraint(
            ["graph_version_id"],
            ["editorial_approvals.graph_version_id"],
            name=op.f("fk_learning_states_graph_version_id_editorial_approvals"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["owners.id"], name=op.f("fk_learning_states_owner_id_owners")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_states")),
        sa.UniqueConstraint(
            "id", "owner_id", "goal_id", name="uq_learning_states_id_owner_goal"
        ),
        sa.UniqueConstraint(
            "owner_id",
            "goal_id",
            "topic_stable_id",
            name="uq_learning_states_goal_topic",
        ),
    )
    op.create_table(
        "personal_overlays",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("goal_id", sa.Text(), nullable=False),
        sa.Column("base_graph_version_id", sa.Text(), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column("row_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "state IN ('active')", name=op.f("ck_personal_overlays_state_valid")
        ),
        sa.ForeignKeyConstraint(
            ["base_graph_version_id"],
            ["editorial_approvals.graph_version_id"],
            name=op.f("fk_personal_overlays_base_graph_version_id_editorial_approvals"),
        ),
        sa.ForeignKeyConstraint(
            ["goal_id", "owner_id"],
            ["goal_workspaces.id", "goal_workspaces.owner_id"],
            name="fk_personal_overlays_goal_owner",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owners.id"],
            name=op.f("fk_personal_overlays_owner_id_owners"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_personal_overlays")),
        sa.UniqueConstraint(
            "id", "owner_id", "goal_id", name="uq_personal_overlays_id_owner_goal"
        ),
        sa.UniqueConstraint(
            "owner_id", "goal_id", name="uq_personal_overlays_owner_goal"
        ),
    )
    op.create_table(
        "diagnostic_preview_edits",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("session_id", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("topic_stable_id", sa.Text(), nullable=True),
        sa.Column("entry_type", sa.Text(), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "entry_type IN ('order_constraint','skip','depth','correction')",
            name=op.f("ck_diagnostic_preview_edits_entry_type_valid"),
        ),
        sa.CheckConstraint(
            "json_type(value_json) = 'object'",
            name=op.f("ck_diagnostic_preview_edits_value_json_object"),
        ),
        sa.CheckConstraint(
            "json_valid(value_json)",
            name=op.f("ck_diagnostic_preview_edits_value_json_valid"),
        ),
        sa.CheckConstraint(
            "sequence >= 1", name=op.f("ck_diagnostic_preview_edits_sequence_positive")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owners.id"],
            name=op.f("fk_diagnostic_preview_edits_owner_id_owners"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id", "owner_id"],
            ["diagnostic_sessions.id", "diagnostic_sessions.owner_id"],
            name="fk_diagnostic_preview_edits_session_owner",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diagnostic_preview_edits")),
        sa.UniqueConstraint(
            "id", "owner_id", name="uq_diagnostic_preview_edits_id_owner"
        ),
        sa.UniqueConstraint(
            "session_id", "sequence", name="uq_diagnostic_preview_edits_sequence"
        ),
    )
    with op.batch_alter_table("diagnostic_preview_edits", schema=None) as batch_op:
        batch_op.create_index(
            "ix_diagnostic_preview_edits_owner_session_sequence",
            ["owner_id", "session_id", "sequence"],
            unique=False,
        )

    op.create_table(
        "overlay_entries",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("goal_id", sa.Text(), nullable=False),
        sa.Column("overlay_id", sa.Text(), nullable=False),
        sa.Column("graph_version_id", sa.Text(), nullable=False),
        sa.Column("topic_stable_id", sa.Text(), nullable=True),
        sa.Column("entry_type", sa.Text(), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("approved_at", sa.Text(), nullable=False),
        sa.Column("supersedes_entry_id", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "entry_type IN ('order_constraint','skip','depth')",
            name=op.f("ck_overlay_entries_entry_type_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('learner','diagnostic_confirmation')",
            name=op.f("ck_overlay_entries_source_valid"),
        ),
        sa.CheckConstraint(
            "json_valid(value_json)", name=op.f("ck_overlay_entries_value_json_valid")
        ),
        sa.ForeignKeyConstraint(
            ["goal_id", "owner_id"],
            ["goal_workspaces.id", "goal_workspaces.owner_id"],
            name="fk_overlay_entries_goal_owner",
        ),
        sa.ForeignKeyConstraint(
            ["graph_version_id"],
            ["editorial_approvals.graph_version_id"],
            name=op.f("fk_overlay_entries_graph_version_id_editorial_approvals"),
        ),
        sa.ForeignKeyConstraint(
            ["overlay_id", "owner_id", "goal_id"],
            [
                "personal_overlays.id",
                "personal_overlays.owner_id",
                "personal_overlays.goal_id",
            ],
            name="fk_overlay_entries_overlay_owner_goal",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["owners.id"], name=op.f("fk_overlay_entries_owner_id_owners")
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_entry_id"],
            ["overlay_entries.id"],
            name=op.f("fk_overlay_entries_supersedes_entry_id_overlay_entries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_overlay_entries")),
        sa.UniqueConstraint(
            "id", "owner_id", "goal_id", name="uq_overlay_entries_id_owner_goal"
        ),
        sa.UniqueConstraint(
            "owner_id",
            "goal_id",
            "content_hash",
            name="uq_overlay_entries_content_hash",
        ),
    )
    with op.batch_alter_table("overlay_entries", schema=None) as batch_op:
        batch_op.create_index(
            "ix_overlay_entries_owner_goal_approved",
            ["owner_id", "goal_id", "approved_at"],
            unique=False,
        )

    op.execute(
        "CREATE TRIGGER trg_overlay_entries_no_update BEFORE UPDATE ON overlay_entries BEGIN SELECT RAISE(ABORT, 'overlay_entries is append-only: UPDATE is not permitted'); END"
    )
    op.execute(
        "CREATE TRIGGER trg_overlay_entries_no_delete BEFORE DELETE ON overlay_entries BEGIN SELECT RAISE(ABORT, 'overlay_entries is append-only: DELETE is not permitted'); END"
    )
    op.execute(
        "CREATE TRIGGER trg_learner_corrections_no_update BEFORE UPDATE ON learner_corrections BEGIN SELECT RAISE(ABORT, 'learner_corrections is append-only: UPDATE is not permitted'); END"
    )
    op.execute(
        "CREATE TRIGGER trg_learner_corrections_no_delete BEFORE DELETE ON learner_corrections BEGIN SELECT RAISE(ABORT, 'learner_corrections is append-only: DELETE is not permitted'); END"
    )

    op.create_table(
        "transferred_evidence_refs",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.Text(), nullable=False),
        sa.Column("goal_id", sa.Text(), nullable=False),
        sa.Column("learning_state_id", sa.Text(), nullable=False),
        sa.Column("source_goal_id", sa.Text(), nullable=False),
        sa.Column("source_evidence_id", sa.Text(), nullable=False),
        sa.Column("classification", sa.Text(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "classification IN ('likely-known','partial','unverified','new')",
            name=op.f("ck_transferred_evidence_refs_classification_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["goal_id", "owner_id"],
            ["goal_workspaces.id", "goal_workspaces.owner_id"],
            name="fk_transferred_evidence_refs_goal_owner",
        ),
        sa.ForeignKeyConstraint(
            ["learning_state_id", "owner_id", "goal_id"],
            [
                "learning_states.id",
                "learning_states.owner_id",
                "learning_states.goal_id",
            ],
            name="fk_transferred_evidence_refs_state_owner_goal",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["owners.id"],
            name=op.f("fk_transferred_evidence_refs_owner_id_owners"),
        ),
        sa.ForeignKeyConstraint(
            ["source_goal_id", "owner_id"],
            ["goal_workspaces.id", "goal_workspaces.owner_id"],
            name="fk_transferred_evidence_refs_source_goal_owner",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transferred_evidence_refs")),
        sa.UniqueConstraint(
            "id",
            "owner_id",
            "goal_id",
            name="uq_transferred_evidence_refs_id_owner_goal",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transferred_evidence_refs")
    op.execute("DROP TRIGGER IF EXISTS trg_learner_corrections_no_delete")
    op.execute("DROP TRIGGER IF EXISTS trg_learner_corrections_no_update")
    op.execute("DROP TRIGGER IF EXISTS trg_overlay_entries_no_delete")
    op.execute("DROP TRIGGER IF EXISTS trg_overlay_entries_no_update")
    with op.batch_alter_table("overlay_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_overlay_entries_owner_goal_approved")

    op.drop_table("overlay_entries")
    with op.batch_alter_table("diagnostic_preview_edits", schema=None) as batch_op:
        batch_op.drop_index("ix_diagnostic_preview_edits_owner_session_sequence")

    op.drop_table("diagnostic_preview_edits")
    op.drop_table("personal_overlays")
    op.drop_table("learning_states")
    op.drop_table("roadmap_idempotency")
    with op.batch_alter_table("learner_corrections", schema=None) as batch_op:
        batch_op.drop_index("ix_learner_corrections_owner_goal_topic")

    op.drop_table("learner_corrections")
    # ### end Alembic commands ###
