/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/canonical/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Canonical Versions
         * @description List every approved canonical graph version.
         */
        get: operations["list_canonical_versions_api_v1_canonical_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/canonical/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Canonical Version
         * @description Fetch one approved canonical graph version with its published topics
         *     and relations. Raises `404` whether the version doesn't exist or just
         *     isn't approved (module docstring).
         */
        get: operations["get_canonical_version_api_v1_canonical_versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Goals */
        get: operations["list_goals_api_v1_goals_get"];
        put?: never;
        /** Post Goal */
        post: operations["post_goal_api_v1_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goal */
        get: operations["get_goal_api_v1_goals__goal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Goal */
        patch: operations["update_goal_api_v1_goals__goal_id__patch"];
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Archive Goal */
        post: operations["post_archive_goal_api_v1_goals__goal_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness/readiness probe. The server only starts once
         *     `api.app.create_app` has confirmed a single Alembic head, so a `200`
         *     here implies the schema is at a known revision.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_api_v1_profile_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CanonicalTopicRelationResponse
         * @description One `TopicRelation` row nested in
         *     `CanonicalVersionDetailResponse.relations`.
         */
        CanonicalTopicRelationResponse: {
            /** From Stable Id */
            from_stable_id: string;
            /** Id */
            id: string;
            /** Rationale */
            rationale: string | null;
            /** Relation Type */
            relation_type: string;
            /** To Stable Id */
            to_stable_id: string;
        };
        /**
         * CanonicalTopicResponse
         * @description One `Topic` row nested in `CanonicalVersionDetailResponse.topics`.
         */
        CanonicalTopicResponse: {
            /** Checkpoint End */
            checkpoint_end: number;
            /** Checkpoint Start */
            checkpoint_start: number;
            /** Level Tag */
            level_tag: string;
            /** Recommended Layer */
            recommended_layer: string;
            /** Scope Tags */
            scope_tags: string[];
            /** Stable Id */
            stable_id: string;
            /** Subject */
            subject: string;
            /** Target Capability */
            target_capability: string;
            /** Title */
            title: string;
        };
        /**
         * CanonicalVersionDetailResponse
         * @description `GET /api/v1/canonical/versions/{id}` response body: the version
         *     plus its published topics and relations (spec §5.2). Nests, rather
         *     than requiring separate topic/relation calls, since a caller reading
         *     one canonical graph version wants its whole shape in one round trip
         *     and both are approval-gated identically (`ports.py`'s
         *     `get_published_topics`/`get_published_relations`).
         */
        CanonicalVersionDetailResponse: {
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Manifest Version */
            manifest_version: string;
            /** Published At */
            published_at: string | null;
            /** Relations */
            relations: components["schemas"]["CanonicalTopicRelationResponse"][];
            /** Supersedes Version Id */
            supersedes_version_id: string | null;
            /** Topics */
            topics: components["schemas"]["CanonicalTopicResponse"][];
            /** Version Label */
            version_label: string;
        };
        /**
         * CanonicalVersionSummaryResponse
         * @description One entry of `GET /api/v1/canonical/versions` (spec §5.2). Mirrors
         *     `modules.canonical.domain.CanonicalGraphVersion`, minus the internal
         *     `creator_owner_id` -- see `yuno.api.routes.canonical` for why callers
         *     never see who ran the offline publisher.
         */
        CanonicalVersionSummaryResponse: {
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Manifest Version */
            manifest_version: string;
            /** Published At */
            published_at: string | null;
            /** Supersedes Version Id */
            supersedes_version_id: string | null;
            /** Version Label */
            version_label: string;
        };
        /**
         * ErrorResponse
         * @description The spec §5.1 error envelope: every `YunoError`, request validation
         *     failure, and unhandled exception renders through this shape (see
         *     `yuno.api.errors.register_exception_handlers`).
         */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Correlation Id */
            correlation_id: string;
            /** Current State */
            current_state?: string | null;
            /** Field Errors */
            field_errors?: components["schemas"]["FieldError"][] | null;
            /** Job Id */
            job_id?: string | null;
            /** Message */
            message: string;
            /** Recovery Action */
            recovery_action?: string | null;
            /** Request Id */
            request_id: string;
            /** Retryable */
            retryable: boolean;
        };
        /**
         * FieldError
         * @description One entry of `ErrorResponse.field_errors`. The domain layer leaves
         *     `YunoError.field_errors` generic (`Sequence[Mapping[str, Any]]`); a
         *     caller must supply mappings with exactly these two keys.
         */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** GoalCreateRequest */
        GoalCreateRequest: {
            /** Graph Version Id */
            graph_version_id: string;
            /** Name */
            name: string;
            path: components["schemas"]["GoalPath"];
            /** Role */
            role?: string | null;
            /** Subject */
            subject?: string | null;
            target_capability: components["schemas"]["TargetCapability"];
            target_level: components["schemas"]["TargetLevel"];
        };
        /** GoalPatchRequest */
        GoalPatchRequest: {
            /** Dismiss Recommendation Key */
            dismiss_recommendation_key?: string | null;
            /** Name */
            name?: string | null;
            resume_destination?: components["schemas"]["ResumeDestination"] | null;
            /** Resume Position */
            resume_position?: string | null;
            /** Role */
            role?: string | null;
            /** Set Current */
            set_current?: boolean | null;
            /** Subject */
            subject?: string | null;
            target_capability?: components["schemas"]["TargetCapability"] | null;
            target_level?: components["schemas"]["TargetLevel"] | null;
        };
        /**
         * GoalPath
         * @enum {string}
         */
        GoalPath: "learn" | "interview_prep";
        /** GoalResponse */
        GoalResponse: {
            /** Created At */
            created_at: string;
            /** Dismissed Recommendation Keys */
            dismissed_recommendation_keys: string[];
            /** Graph Version Id */
            graph_version_id: string;
            /** Id */
            id: string;
            /** Last Accessed At */
            last_accessed_at: string | null;
            /** Name */
            name: string;
            path: components["schemas"]["GoalPath"];
            resume_destination: components["schemas"]["ResumeDestination"] | null;
            /** Resume Position */
            resume_position: string | null;
            /** Role */
            role: string | null;
            /** Row Version */
            row_version: number;
            status: components["schemas"]["GoalStatus"];
            /** Subject */
            subject: string | null;
            target_capability: components["schemas"]["TargetCapability"];
            target_level: components["schemas"]["TargetLevel"];
            /** Updated At */
            updated_at: string;
        };
        /**
         * GoalStatus
         * @enum {string}
         */
        GoalStatus: "active" | "archived";
        /**
         * HealthResponse
         * @description `GET /api/v1/health` response body.
         */
        HealthResponse: {
            /** Schema Revision */
            schema_revision: string;
            /** Status */
            status: string;
        };
        /** LearnerProfilePatchRequest */
        LearnerProfilePatchRequest: {
            /** Experience */
            experience?: string | null;
            /** Strengths */
            strengths?: string | null;
            /** Weaknesses */
            weaknesses?: string | null;
        };
        /** LearnerProfileResponse */
        LearnerProfileResponse: {
            /** Current Goal Id */
            current_goal_id: string | null;
            /** Experience */
            experience: string | null;
            /** Profile Revision */
            profile_revision: number;
            /** Strengths */
            strengths: string | null;
            /** Updated At */
            updated_at: string;
            /** Weaknesses */
            weaknesses: string | null;
        };
        /**
         * ResumeDestination
         * @enum {string}
         */
        ResumeDestination: "/app/learn-roadmap" | "/app/topic-studio" | "/app/interview-hub" | "/app/practice" | "/app/mock";
        /**
         * TargetCapability
         * @enum {string}
         */
        TargetCapability: "know" | "understand" | "choose" | "implement" | "diagnose" | "defend";
        /**
         * TargetLevel
         * @enum {string}
         */
        TargetLevel: "Mid-level" | "Senior" | "Staff";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_canonical_versions_api_v1_canonical_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalVersionSummaryResponse"][];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_canonical_version_api_v1_canonical_versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalVersionDetailResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_goals_api_v1_goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"][];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_goal_api_v1_goals_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_goal_api_v1_goals__goal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_goal_api_v1_goals__goal_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_archive_goal_api_v1_goals__goal_id__archive_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "Idempotency-Key"?: string | null;
            };
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_profile_api_v1_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnerProfileResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_profile_api_v1_profile_patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearnerProfilePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnerProfileResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
