/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/artifacts/{artifact_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate Artifact */
        post: operations["regenerate_artifact_api_v1_artifacts__artifact_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/bridges/{proposal_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Bridge Decision */
        post: operations["post_bridge_decision_api_v1_bridges__proposal_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/canonical/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Canonical Versions
         * @description List every approved canonical graph version.
         */
        get: operations["list_canonical_versions_api_v1_canonical_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/canonical/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Canonical Version
         * @description Fetch one approved canonical graph version with its published topics
         *     and relations. Raises `404` whether the version doesn't exist or just
         *     isn't approved (module docstring).
         */
        get: operations["get_canonical_version_api_v1_canonical_versions__version_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Diagnostic */
        post: operations["post_diagnostic_api_v1_diagnostics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Active Diagnostic Session
         * @description Return the server-persisted onboarding session, if one exists.
         *
         *     The client deliberately keeps no diagnostic identifier in browser
         *     storage. A cleared browser therefore resumes from the same durable
         *     server state instead of silently starting another onboarding flow.
         */
        get: operations["get_active_diagnostic_session_api_v1_diagnostics_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Diagnostic Session */
        get: operations["get_diagnostic_session_api_v1_diagnostics__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Diagnostic Session */
        patch: operations["update_diagnostic_session_api_v1_diagnostics__session_id__patch"];
        trace?: never;
    };
    "/api/v1/diagnostics/{session_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Diagnostic Answer */
        post: operations["post_diagnostic_answer_api_v1_diagnostics__session_id__answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/{session_id}/confirm-goal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Confirm Goal
         * @description Atomically turn a persisted preview into a complete goal workspace.
         */
        post: operations["post_confirm_goal_api_v1_diagnostics__session_id__confirm_goal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/{session_id}/roadmap-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Roadmap Preview */
        get: operations["get_roadmap_preview_api_v1_diagnostics__session_id__roadmap_preview_get"];
        /** Put Roadmap Preview */
        put: operations["put_roadmap_preview_api_v1_diagnostics__session_id__roadmap_preview_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Goals */
        get: operations["list_goals_api_v1_goals_get"];
        put?: never;
        /** Post Goal */
        post: operations["post_goal_api_v1_goals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goal */
        get: operations["get_goal_api_v1_goals__goal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Goal */
        patch: operations["update_goal_api_v1_goals__goal_id__patch"];
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Archive Goal */
        post: operations["post_archive_goal_api_v1_goals__goal_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/corrections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Correction */
        post: operations["post_correction_api_v1_goals__goal_id__corrections_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Goal Delete */
        post: operations["post_goal_delete_api_v1_goals__goal_id__delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/delete-preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Goal Delete Preflight */
        post: operations["post_goal_delete_preflight_api_v1_goals__goal_id__delete_preflight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/depth-overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Depth */
        post: operations["post_depth_api_v1_goals__goal_id__depth_overrides_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/learning-states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Learning States */
        get: operations["get_learning_states_api_v1_goals__goal_id__learning_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/order-constraints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Order Constraint */
        post: operations["post_order_constraint_api_v1_goals__goal_id__order_constraints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/overlay-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Overlay Proposals */
        get: operations["get_overlay_proposals_api_v1_goals__goal_id__overlay_proposals_get"];
        put?: never;
        /** Post Overlay Proposal */
        post: operations["post_overlay_proposal_api_v1_goals__goal_id__overlay_proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/roadmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goal Roadmap */
        get: operations["get_goal_roadmap_api_v1_goals__goal_id__roadmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/skip-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Skip */
        post: operations["post_skip_api_v1_goals__goal_id__skip_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/topics/{topic_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Topic Layer */
        post: operations["generate_topic_layer_api_v1_goals__goal_id__topics__topic_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/topics/{topic_id}/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Topic Layers */
        get: operations["get_topic_layers_api_v1_goals__goal_id__topics__topic_id__layers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/goals/{goal_id}/topics/{topic_id}/layers/{layer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Topic Layer */
        get: operations["get_topic_layer_api_v1_goals__goal_id__topics__topic_id__layers__layer__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness/readiness probe. The server only starts once
         *     `api.app.create_app` has confirmed a single Alembic head, so a `200`
         *     here implies the schema is at a known revision.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import-statements/{statement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Import Statement */
        patch: operations["patch_import_statement_api_v1_import_statements__statement_id__patch"];
        trace?: never;
    };
    "/api/v1/import-statements/{statement_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Import Statement Dismiss */
        post: operations["post_import_statement_dismiss_api_v1_import_statements__statement_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import-statements/{statement_id}/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Import Statement Map */
        post: operations["post_import_statement_map_api_v1_import_statements__statement_id__map_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/import-statements/{statement_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Import Statement Verify */
        post: operations["post_import_statement_verify_api_v1_import_statements__statement_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Imports */
        get: operations["get_imports_api_v1_imports_get"];
        put?: never;
        /** Post Import */
        post: operations["post_import_api_v1_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import Record */
        get: operations["get_import_record_api_v1_imports__import_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{import_id}/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Import Parse */
        post: operations["post_import_parse_api_v1_imports__import_id__parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{import_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Import Reprocess */
        post: operations["post_import_reprocess_api_v1_imports__import_id__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/imports/{import_id}/statements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import Statements */
        get: operations["get_import_statements_api_v1_imports__import_id__statements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/overlay-proposals/{proposal_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Overlay Proposal Decision */
        post: operations["post_overlay_proposal_decision_api_v1_overlay_proposals__proposal_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Profile */
        get: operations["get_profile_api_v1_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_api_v1_profile_patch"];
        trace?: never;
    };
    "/api/v1/topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Topic Detail */
        get: operations["get_topic_detail_api_v1_topics__topic_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CanonicalTopicRelationResponse
         * @description One `TopicRelation` row nested in
         *     `CanonicalVersionDetailResponse.relations`.
         */
        CanonicalTopicRelationResponse: {
            /** From Stable Id */
            from_stable_id: string;
            /** Id */
            id: string;
            /** Rationale */
            rationale: string | null;
            /** Relation Type */
            relation_type: string;
            /** To Stable Id */
            to_stable_id: string;
        };
        /**
         * CanonicalTopicResponse
         * @description One `Topic` row nested in `CanonicalVersionDetailResponse.topics`.
         */
        CanonicalTopicResponse: {
            /** Checkpoint End */
            checkpoint_end: number;
            /** Checkpoint Start */
            checkpoint_start: number;
            /** Level Tag */
            level_tag: string;
            /** Recommended Layer */
            recommended_layer: string;
            /** Scope Tags */
            scope_tags: string[];
            /** Stable Id */
            stable_id: string;
            /** Subject */
            subject: string;
            /** Target Capability */
            target_capability: string;
            /** Title */
            title: string;
        };
        /**
         * CanonicalVersionDetailResponse
         * @description `GET /api/v1/canonical/versions/{id}` response body: the version
         *     plus its published topics and relations (spec §5.2). Nests, rather
         *     than requiring separate topic/relation calls, since a caller reading
         *     one canonical graph version wants its whole shape in one round trip
         *     and both are approval-gated identically (`ports.py`'s
         *     `get_published_topics`/`get_published_relations`).
         */
        CanonicalVersionDetailResponse: {
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Manifest Version */
            manifest_version: string;
            /** Published At */
            published_at: string | null;
            /** Relations */
            relations: components["schemas"]["CanonicalTopicRelationResponse"][];
            /** Supersedes Version Id */
            supersedes_version_id: string | null;
            /** Topics */
            topics: components["schemas"]["CanonicalTopicResponse"][];
            /** Version Label */
            version_label: string;
        };
        /**
         * CanonicalVersionSummaryResponse
         * @description One entry of `GET /api/v1/canonical/versions` (spec §5.2). Mirrors
         *     `modules.canonical.domain.CanonicalGraphVersion`, minus the internal
         *     `creator_owner_id` -- see `yuno.api.routes.canonical` for why callers
         *     never see who ran the offline publisher.
         */
        CanonicalVersionSummaryResponse: {
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Manifest Version */
            manifest_version: string;
            /** Published At */
            published_at: string | null;
            /** Supersedes Version Id */
            supersedes_version_id: string | null;
            /** Version Label */
            version_label: string;
        };
        /**
         * Capability
         * @enum {string}
         */
        Capability: "know" | "understand" | "choose" | "implement" | "diagnose" | "defend";
        /**
         * CorrectionType
         * @enum {string}
         */
        CorrectionType: "correction" | "confirmation" | "gap" | "transfer-confirmation";
        /** DepthOverrideRequest */
        DepthOverrideRequest: {
            /** Depth */
            depth: string | null;
            /** Reason */
            reason?: string | null;
            /** Topic Stable Id */
            topic_stable_id: string;
        };
        /**
         * DiagnosticAction
         * @enum {string}
         */
        DiagnosticAction: "pause" | "resume" | "skip_diagnostic" | "skip_notes" | "open_roadmap_preview" | "retry";
        /** DiagnosticAnswerRequest */
        DiagnosticAnswerRequest: {
            /** Answer */
            answer: string;
            confidence: components["schemas"]["DiagnosticConfidence"];
            /** Question Ref */
            question_ref: string;
        };
        /** DiagnosticAnswerResponse */
        DiagnosticAnswerResponse: {
            /** Adaptive Context Version */
            adaptive_context_version: string;
            /** Answer */
            answer: string;
            /** Answered At */
            answered_at: string;
            confidence: components["schemas"]["DiagnosticConfidence"];
            /** Id */
            id: string;
            /** Question Ref */
            question_ref: string;
            /** Sequence */
            sequence: number;
        };
        /**
         * DiagnosticConfidence
         * @enum {string}
         */
        DiagnosticConfidence: "low" | "medium" | "high";
        /** DiagnosticCreateRequest */
        DiagnosticCreateRequest: {
            /** Graph Version Id */
            graph_version_id: string;
            path: components["schemas"]["DiagnosticPath"];
            /** Role */
            role?: string | null;
            /** Setup Inputs */
            setup_inputs?: {
                [key: string]: unknown;
            };
            /** Subject */
            subject?: string | null;
            target_capability: components["schemas"]["DiagnosticTargetCapability"];
            target_level: components["schemas"]["DiagnosticTargetLevel"];
        };
        /** DiagnosticPatchRequest */
        DiagnosticPatchRequest: {
            action?: components["schemas"]["DiagnosticAction"] | null;
            /** Untrusted Seed Text */
            untrusted_seed_text?: string | null;
        };
        /**
         * DiagnosticPath
         * @enum {string}
         */
        DiagnosticPath: "learn" | "interview_prep";
        /** DiagnosticPreviewEditRequest */
        DiagnosticPreviewEditRequest: {
            /** Entry Type */
            entry_type: string;
            /** Reason */
            reason?: string | null;
            /** Topic Stable Id */
            topic_stable_id?: string | null;
            /** Value */
            value: {
                [key: string]: unknown;
            };
        };
        /** DiagnosticQuestionResponse */
        DiagnosticQuestionResponse: {
            /** Adaptive Context Version */
            adaptive_context_version: string;
            /** Prompt */
            prompt: string;
            /** Ref */
            ref: string;
            /** Sequence */
            sequence: number;
        };
        /** DiagnosticResponse */
        DiagnosticResponse: {
            /** Answers */
            answers: components["schemas"]["DiagnosticAnswerResponse"][];
            /** Captured Graph Version Id */
            captured_graph_version_id: string;
            /** Confirmed Goal Id */
            confirmed_goal_id: string | null;
            /** Created At */
            created_at: string;
            /** Diagnostic Skipped */
            diagnostic_skipped: boolean;
            /** Expires At */
            expires_at: string | null;
            /** Failure Code */
            failure_code: string | null;
            /** Failure Reference */
            failure_reference: string | null;
            /** Id */
            id: string;
            next_question: components["schemas"]["DiagnosticQuestionResponse"] | null;
            /** Paused At */
            paused_at: string | null;
            /** Question Set Version */
            question_set_version: string;
            /** Row Version */
            row_version: number;
            /** Seed Skipped */
            seed_skipped: boolean;
            /** Setup Inputs */
            setup_inputs: {
                [key: string]: unknown;
            };
            /** Started At */
            started_at: string | null;
            state: components["schemas"]["DiagnosticState"];
            untrusted_seed_kind: components["schemas"]["UntrustedSeedKind"] | null;
            /** Untrusted Seed Text */
            untrusted_seed_text: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** DiagnosticRoadmapPreviewResponse */
        DiagnosticRoadmapPreviewResponse: {
            /** Answer Count */
            answer_count: number;
            /** Captured Graph Version Id */
            captured_graph_version_id: string;
            /** Diagnostic Skipped */
            diagnostic_skipped: boolean;
            /** Projection Version */
            projection_version: string;
            /** Saved Edits */
            saved_edits: {
                [key: string]: unknown;
            }[];
            /** Session Id */
            session_id: string;
            state: components["schemas"]["DiagnosticState"];
            /** Topic Recommendations */
            topic_recommendations: {
                [key: string]: unknown;
            }[];
        };
        /** DiagnosticRoadmapPreviewUpdateRequest */
        DiagnosticRoadmapPreviewUpdateRequest: {
            /** Edits */
            edits?: components["schemas"]["DiagnosticPreviewEditRequest"][];
        };
        /**
         * DiagnosticState
         * @enum {string}
         */
        DiagnosticState: "not-started" | "in-progress" | "paused" | "skipped" | "resumed" | "roadmap-preview" | "confirmed" | "failed";
        /**
         * DiagnosticTargetCapability
         * @enum {string}
         */
        DiagnosticTargetCapability: "know" | "understand" | "choose" | "implement" | "diagnose" | "defend";
        /**
         * DiagnosticTargetLevel
         * @enum {string}
         */
        DiagnosticTargetLevel: "Mid-level" | "Senior" | "Staff";
        /**
         * ErrorResponse
         * @description The spec §5.1 error envelope: every `YunoError`, request validation
         *     failure, and unhandled exception renders through this shape (see
         *     `yuno.api.errors.register_exception_handlers`).
         */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Correlation Id */
            correlation_id: string;
            /** Current State */
            current_state?: string | null;
            /** Field Errors */
            field_errors?: components["schemas"]["FieldError"][] | null;
            /** Job Id */
            job_id?: string | null;
            /** Message */
            message: string;
            /** Recovery Action */
            recovery_action?: string | null;
            /** Request Id */
            request_id: string;
            /** Retryable */
            retryable: boolean;
        };
        /**
         * FieldError
         * @description One entry of `ErrorResponse.field_errors`. The domain layer leaves
         *     `YunoError.field_errors` generic (`Sequence[Mapping[str, Any]]`); a
         *     caller must supply mappings with exactly these two keys.
         */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** GoalCreateRequest */
        GoalCreateRequest: {
            /** Graph Version Id */
            graph_version_id: string;
            /** Name */
            name: string;
            path: components["schemas"]["GoalPath"];
            /** Role */
            role?: string | null;
            /** Subject */
            subject?: string | null;
            target_capability: components["schemas"]["TargetCapability"];
            target_level: components["schemas"]["TargetLevel"];
        };
        /** GoalDeleteImpactResponse */
        GoalDeleteImpactResponse: {
            /** Evidence Ids */
            evidence_ids: string[];
            /** Goal Id */
            goal_id: string;
            /** Learning State Ids */
            learning_state_ids: string[];
            /** Snapshot Id */
            snapshot_id: string;
        };
        /** GoalDeleteRequest */
        GoalDeleteRequest: {
            /** Snapshot Id */
            snapshot_id: string;
        };
        /** GoalPatchRequest */
        GoalPatchRequest: {
            /** Dismiss Recommendation Key */
            dismiss_recommendation_key?: string | null;
            /** Name */
            name?: string | null;
            resume_destination?: components["schemas"]["ResumeDestination"] | null;
            /** Resume Position */
            resume_position?: string | null;
            /** Role */
            role?: string | null;
            /** Set Current */
            set_current?: boolean | null;
            /** Subject */
            subject?: string | null;
            target_capability?: components["schemas"]["TargetCapability"] | null;
            target_level?: components["schemas"]["TargetLevel"] | null;
        };
        /**
         * GoalPath
         * @enum {string}
         */
        GoalPath: "learn" | "interview_prep";
        /** GoalResponse */
        GoalResponse: {
            /** Created At */
            created_at: string;
            /** Dismissed Recommendation Keys */
            dismissed_recommendation_keys: string[];
            /** Graph Version Id */
            graph_version_id: string;
            /** Id */
            id: string;
            /** Last Accessed At */
            last_accessed_at: string | null;
            /** Name */
            name: string;
            path: components["schemas"]["GoalPath"];
            resume_destination: components["schemas"]["ResumeDestination"] | null;
            /** Resume Position */
            resume_position: string | null;
            /** Role */
            role: string | null;
            /** Row Version */
            row_version: number;
            status: components["schemas"]["GoalStatus"];
            /** Subject */
            subject: string | null;
            target_capability: components["schemas"]["TargetCapability"];
            target_level: components["schemas"]["TargetLevel"];
            /** Updated At */
            updated_at: string;
        };
        /**
         * GoalStatus
         * @enum {string}
         */
        GoalStatus: "active" | "archived" | "tombstoned";
        /**
         * HealthResponse
         * @description `GET /api/v1/health` response body.
         */
        HealthResponse: {
            /** Schema Revision */
            schema_revision: string;
            /** Status */
            status: string;
        };
        /** ImportCreateRequest */
        ImportCreateRequest: {
            /** Goal Id */
            goal_id?: string | null;
            import_type: components["schemas"]["ImportType"];
            /** Original Content */
            original_content: string;
        };
        /** ImportRecordResponse */
        ImportRecordResponse: {
            /** Created At */
            created_at: string;
            /** Failure Code */
            failure_code: string | null;
            /** Failure Reference */
            failure_reference: string | null;
            /** Goal Id */
            goal_id: string | null;
            /** Id */
            id: string;
            import_type: components["schemas"]["ImportType"];
            /** Original Content */
            original_content: string;
            /** Original Hash */
            original_hash: string;
            /** Parser Version */
            parser_version: string;
            /** Row Version */
            row_version: number;
            status: components["schemas"]["ImportStatus"];
            /** Updated At */
            updated_at: string;
        };
        /** ImportStatementMapRequest */
        ImportStatementMapRequest: {
            /** Goal Id */
            goal_id: string;
            /** Topic Id */
            topic_id: string;
        };
        /** ImportStatementMapResponse */
        ImportStatementMapResponse: {
            mapping: components["schemas"]["ImportStatementMappingResponse"];
            statement: components["schemas"]["ImportStatementResponse"];
            topic_imports_hash: components["schemas"]["TopicImportHashResponse"];
        };
        /** ImportStatementMappingResponse */
        ImportStatementMappingResponse: {
            /** Accepted At */
            accepted_at: string;
            decision: components["schemas"]["MappingDecision"];
            /** Goal Id */
            goal_id: string;
            /** Graph Version Id */
            graph_version_id: string;
            /** Revoked At */
            revoked_at: string | null;
            /** Topic Id */
            topic_id: string;
        };
        /** ImportStatementPatchRequest */
        ImportStatementPatchRequest: {
            /** Corrected Text */
            corrected_text: string;
        };
        /** ImportStatementResponse */
        ImportStatementResponse: {
            /** Confidence */
            confidence: number;
            /** Corrected Text */
            corrected_text: string | null;
            /** Created At */
            created_at: string;
            /** Duplicate Of Statement Id */
            duplicate_of_statement_id: string | null;
            /** Id */
            id: string;
            /** Import Id */
            import_id: string;
            mapping?: components["schemas"]["ImportStatementMappingResponse"] | null;
            mapping_state: components["schemas"]["MappingState"];
            /** Normalized Hash */
            normalized_hash: string;
            /** Normalized Text */
            normalized_text: string;
            /** Original Hash */
            original_hash: string;
            /** Original Text */
            original_text: string;
            /** Parser Version */
            parser_version: string;
            /** Row Version */
            row_version: number;
            /** Sequence */
            sequence: number;
            trust_state: components["schemas"]["TrustState"];
            /** Updated At */
            updated_at: string;
        };
        /**
         * ImportStatus
         * @enum {string}
         */
        ImportStatus: "selected" | "parsing" | "parsed-untrusted" | "learner-review" | "applied" | "failed" | "cancelled";
        /**
         * ImportType
         * @enum {string}
         */
        ImportType: "markdown" | "plain_text";
        /**
         * JobRefResponse
         * @description Mirrors `application.jobs.JobRef` — the `202` enqueue response body
         *     every async endpoint returns via `accepted_job`.
         */
        JobRefResponse: {
            /**
             * Deduplicated
             * @default false
             */
            deduplicated: boolean;
            /** Enqueued At */
            enqueued_at: string;
            /** Job Id */
            job_id: string;
            /** Kind */
            kind: string;
            status: components["schemas"]["JobStatus"];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        /**
         * LayerState
         * @enum {string}
         */
        LayerState: "ready" | "empty" | "stale" | "unavailable";
        /** LearnerCorrectionRequest */
        LearnerCorrectionRequest: {
            classification: components["schemas"]["LearningClassification"];
            /** @default correction */
            correction_type: components["schemas"]["CorrectionType"];
            /** Reason */
            reason?: string | null;
            /** Topic Stable Id */
            topic_stable_id: string;
        };
        /** LearnerProfilePatchRequest */
        LearnerProfilePatchRequest: {
            /** Experience */
            experience?: string | null;
            /** Strengths */
            strengths?: string | null;
            /** Weaknesses */
            weaknesses?: string | null;
        };
        /** LearnerProfileResponse */
        LearnerProfileResponse: {
            /** Current Goal Id */
            current_goal_id: string | null;
            /** Experience */
            experience: string | null;
            /** Profile Revision */
            profile_revision: number;
            /** Strengths */
            strengths: string | null;
            /** Updated At */
            updated_at: string;
            /** Weaknesses */
            weaknesses: string | null;
        };
        /**
         * LearningClassification
         * @enum {string}
         */
        LearningClassification: "likely-known" | "partial" | "unverified" | "new";
        /** LearningStateResponse */
        LearningStateResponse: {
            classification: components["schemas"]["LearningClassification"];
            corrected_classification?: components["schemas"]["LearningClassification"] | null;
            /** Explanation */
            explanation: string;
            /** Origin */
            origin: string;
            /** Recommended Depth */
            recommended_depth: string;
            /** Topic Stable Id */
            topic_stable_id: string;
        };
        /**
         * MappingDecision
         * @enum {string}
         */
        MappingDecision: "approved" | "revoked";
        /**
         * MappingState
         * @enum {string}
         */
        MappingState: "unmapped" | "mapped" | "duplicate";
        /** OrderConstraintRequest */
        OrderConstraintRequest: {
            /** After Topic Id */
            after_topic_id: string;
            /** Before Topic Id */
            before_topic_id: string;
            /** Reason */
            reason?: string | null;
        };
        /**
         * OverlayDecisionType
         * @enum {string}
         */
        OverlayDecisionType: "accept" | "add" | "postpone" | "dismiss";
        /** OverlayProposalCreateRequest */
        OverlayProposalCreateRequest: {
            /** Generated Against Graph Version Id */
            generated_against_graph_version_id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            proposal_type: components["schemas"]["OverlayProposalType"];
            /** Topic Stable Id */
            topic_stable_id?: string | null;
        };
        /** OverlayProposalDecisionRequest */
        OverlayProposalDecisionRequest: {
            decision: components["schemas"]["OverlayDecisionType"];
            /** Reason */
            reason?: string | null;
        };
        /** OverlayProposalDecisionResponse */
        OverlayProposalDecisionResponse: {
            /** Decided At */
            decided_at: string;
            decision: components["schemas"]["OverlayDecisionType"];
            /** Id */
            id: string;
            /** Reason */
            reason: string | null;
        };
        /** OverlayProposalResponse */
        OverlayProposalResponse: {
            /** Content Hash */
            content_hash: string;
            /** Created At */
            created_at: string;
            /** Decided At */
            decided_at: string | null;
            /** Decisions */
            decisions?: components["schemas"]["OverlayProposalDecisionResponse"][];
            /**
             * Deduplicated
             * @default false
             */
            deduplicated: boolean;
            /** Generated Against Graph Version Id */
            generated_against_graph_version_id: string;
            /** Goal Id */
            goal_id: string;
            /** Id */
            id: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            proposal_type: components["schemas"]["OverlayProposalType"];
            state: components["schemas"]["OverlayProposalState"];
            /** State Reason */
            state_reason: string | null;
            /** Topic Stable Id */
            topic_stable_id: string | null;
        };
        /**
         * OverlayProposalState
         * @enum {string}
         */
        OverlayProposalState: "awaiting-learner-decision" | "accepted" | "postponed" | "dismissed" | "rejected-stale";
        /**
         * OverlayProposalType
         * @enum {string}
         */
        OverlayProposalType: "recommendation" | "emphasis" | "example" | "exercise" | "ordering" | "bridge";
        /**
         * ResumeDestination
         * @enum {string}
         */
        ResumeDestination: "/app/learn-roadmap" | "/app/topic-studio" | "/app/interview-hub" | "/app/practice" | "/app/mock";
        /** RoadmapMutationResponse */
        RoadmapMutationResponse: {
            /**
             * Checkpoint Saved
             * @default true
             */
            checkpoint_saved: boolean;
            projection: components["schemas"]["RoadmapResponse"];
        };
        /** RoadmapResponse */
        RoadmapResponse: {
            /** Goal Id */
            goal_id: string;
            /** Graph Version Id */
            graph_version_id: string;
            /** Projection Version */
            projection_version: string;
            /** State */
            state: string;
            /** Topics */
            topics: components["schemas"]["RoadmapTopicResponse"][];
        };
        /** RoadmapTopicResponse */
        RoadmapTopicResponse: {
            classification: components["schemas"]["LearningClassification"];
            /** Conflicts */
            conflicts: {
                [key: string]: unknown;
            }[];
            /** Depth Override */
            depth_override: string | null;
            /** Explanation */
            explanation: string;
            /** Has Transferred Evidence */
            has_transferred_evidence: boolean;
            /** Is Skipped */
            is_skipped: boolean;
            /** Level Tag */
            level_tag: string;
            /** Pending Proposals */
            pending_proposals: {
                [key: string]: unknown;
            }[];
            /** Recommended Depth */
            recommended_depth: string;
            /** Scope Tags */
            scope_tags: string[];
            /** Stable Id */
            stable_id: string;
            /** Subject */
            subject: string;
            /** Target Capability */
            target_capability: string;
            /** Title */
            title: string;
        };
        /** SkipDecisionRequest */
        SkipDecisionRequest: {
            /** Reason */
            reason?: string | null;
            /** Skipped */
            skipped: boolean;
            /** Topic Stable Id */
            topic_stable_id: string;
        };
        /**
         * TargetCapability
         * @enum {string}
         */
        TargetCapability: "know" | "understand" | "choose" | "implement" | "diagnose" | "defend";
        /**
         * TargetLevel
         * @enum {string}
         */
        TargetLevel: "Mid-level" | "Senior" | "Staff";
        /** TopicCheckpointResponse */
        TopicCheckpointResponse: {
            /** Assumptions */
            assumptions: string[];
            /** Constraints */
            constraints: string[];
            /** Estimated Minutes */
            estimated_minutes: number;
            /** Evidence Criterion */
            evidence_criterion: string;
            /** Expected Artifact */
            expected_artifact: string;
            /** Limitation */
            limitation: string;
            /** Rubric */
            rubric: string[];
            /** Scenario */
            scenario: string;
            target_capability: components["schemas"]["Capability"];
        };
        /** TopicDetailResponse */
        TopicDetailResponse: {
            /** Graph Version Id */
            graph_version_id: string;
            /** Level Tag */
            level_tag: string;
            /** Recommended Layer */
            recommended_layer: string;
            /** Scope Tags */
            scope_tags: string[];
            /** Stable Id */
            stable_id: string;
            /** Subject */
            subject: string;
            target_capability: components["schemas"]["Capability"];
            /** Title */
            title: string;
        };
        /** TopicImportHashResponse */
        TopicImportHashResponse: {
            /** Goal Id */
            goal_id: string;
            /** Graph Version Id */
            graph_version_id: string;
            /** Imports Hash */
            imports_hash: string;
            /** Topic Id */
            topic_id: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * TopicLayer
         * @enum {string}
         */
        TopicLayer: "Essential" | "Implementation" | "Internals" | "Production" | "Alternatives" | "Failures" | "Interview" | "Sources";
        /** TopicLayerResponse */
        TopicLayerResponse: {
            checkpoint: components["schemas"]["TopicCheckpointResponse"] | null;
            layer: components["schemas"]["TopicLayer"];
            /** Markdown */
            markdown: string | null;
            /** Markdown Hash */
            markdown_hash: string | null;
            /** Revision Id */
            revision_id: string | null;
            state: components["schemas"]["LayerState"];
        };
        /** TopicLayersResponse */
        TopicLayersResponse: {
            /** Conversation Scope */
            conversation_scope: string;
            /** Goal Id */
            goal_id: string;
            /** Graph Version Id */
            graph_version_id: string;
            /** Layers */
            layers: components["schemas"]["TopicLayerResponse"][];
            /** Topic Id */
            topic_id: string;
        };
        /**
         * TrustState
         * @enum {string}
         */
        TrustState: "untrusted" | "verified" | "dismissed";
        /**
         * UntrustedSeedKind
         * @enum {string}
         */
        UntrustedSeedKind: "notes" | "questions";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    regenerate_artifact_api_v1_artifacts__artifact_id__regenerate_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                artifact_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRefResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_bridge_decision_api_v1_bridges__proposal_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverlayProposalDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverlayProposalResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_canonical_versions_api_v1_canonical_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalVersionSummaryResponse"][];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_canonical_version_api_v1_canonical_versions__version_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CanonicalVersionDetailResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_diagnostic_api_v1_diagnostics_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnosticCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_active_diagnostic_session_api_v1_diagnostics_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticResponse"] | null;
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_diagnostic_session_api_v1_diagnostics__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_diagnostic_session_api_v1_diagnostics__session_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnosticPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_diagnostic_answer_api_v1_diagnostics__session_id__answers_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnosticAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticAnswerResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_confirm_goal_api_v1_diagnostics__session_id__confirm_goal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_roadmap_preview_api_v1_diagnostics__session_id__roadmap_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticRoadmapPreviewResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    put_roadmap_preview_api_v1_diagnostics__session_id__roadmap_preview_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnosticRoadmapPreviewUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticRoadmapPreviewResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_goals_api_v1_goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"][];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_goal_api_v1_goals_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_goal_api_v1_goals__goal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_goal_api_v1_goals__goal_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_archive_goal_api_v1_goals__goal_id__archive_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "Idempotency-Key"?: string | null;
            };
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_correction_api_v1_goals__goal_id__corrections_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearnerCorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapMutationResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_goal_delete_api_v1_goals__goal_id__delete_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoalDeleteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalDeleteImpactResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_goal_delete_preflight_api_v1_goals__goal_id__delete_preflight_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoalDeleteImpactResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_depth_api_v1_goals__goal_id__depth_overrides_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepthOverrideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapMutationResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_learning_states_api_v1_goals__goal_id__learning_states_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearningStateResponse"][];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_order_constraint_api_v1_goals__goal_id__order_constraints_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderConstraintRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapMutationResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_overlay_proposals_api_v1_goals__goal_id__overlay_proposals_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverlayProposalResponse"][];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_overlay_proposal_api_v1_goals__goal_id__overlay_proposals_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverlayProposalCreateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverlayProposalResponse"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverlayProposalResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_goal_roadmap_api_v1_goals__goal_id__roadmap_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_skip_api_v1_goals__goal_id__skip_decisions_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                goal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapMutationResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    generate_topic_layer_api_v1_goals__goal_id__topics__topic_id__generate_post: {
        parameters: {
            query: {
                layer: components["schemas"]["TopicLayer"];
            };
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                goal_id: string;
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRefResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_topic_layers_api_v1_goals__goal_id__topics__topic_id__layers_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicLayersResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_topic_layer_api_v1_goals__goal_id__topics__topic_id__layers__layer__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                goal_id: string;
                topic_id: string;
                layer: components["schemas"]["TopicLayer"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicLayerResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_import_statement_api_v1_import_statements__statement_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "Idempotency-Key"?: string | null;
            };
            path: {
                statement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportStatementPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportStatementResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_import_statement_dismiss_api_v1_import_statements__statement_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "Idempotency-Key"?: string | null;
            };
            path: {
                statement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportStatementResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_import_statement_map_api_v1_import_statements__statement_id__map_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "Idempotency-Key"?: string | null;
            };
            path: {
                statement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportStatementMapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportStatementMapResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_import_statement_verify_api_v1_import_statements__statement_id__verify_post: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "Idempotency-Key"?: string | null;
            };
            path: {
                statement_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportStatementResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_imports_api_v1_imports_get: {
        parameters: {
            query?: {
                goal_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportRecordResponse"][];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_import_api_v1_imports_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportRecordResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_import_record_api_v1_imports__import_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportRecordResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_import_parse_api_v1_imports__import_id__parse_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRefResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_import_reprocess_api_v1_imports__import_id__reprocess_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRefResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_import_statements_api_v1_imports__import_id__statements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportStatementResponse"][];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_overlay_proposal_decision_api_v1_overlay_proposals__proposal_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverlayProposalDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverlayProposalResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_profile_api_v1_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnerProfileResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_profile_api_v1_profile_patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearnerProfilePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnerProfileResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_topic_detail_api_v1_topics__topic_id__get: {
        parameters: {
            query: {
                graph_version: string;
            };
            header?: never;
            path: {
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicDetailResponse"];
                };
            };
            /** @description Default Response */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
